apiVersion: v1
kind: Service
metadata:
  name: myserviccc2

spec:
  # type: NodePort
  type: ClusterIP
  selector:
    env: dev
  ports:
    - port: 3000
      
      targetPort: 80
      # nodePort: 80