apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev

  template:
    metadata:
      labels:
        env: dev 
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
         - containerPort: 80
      


      