apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test
spec:
  Replicas: 3
  selector:
    matchLabels:

     env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx