apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: testt
spec:
  selector:
    matchLabels:
      env: prod

  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: nginx
          image: nginx