# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: test
# spec:
#   template:
#     spec:
#       containers:
#         - name: alpine
#           image: alpine
#           command: ["sleep" , "80"]
#       restartPolicy: Never

apiVersion: batch/v1
kind: Job
metadata:
  name: test2
spec:
  completions: 4
  parallelism: 2

  template:
    spec:
      containers:
        - name: alpine
          image: alpine
          command: ["sleep" , "80"]
      restartPolicy: Never