################ requird################

apiVersion: v1
kind: Pod

metadata:
 name: podten
spec:
    containers:
      - name: nginx

        image: nginx
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:    
              
            -  matchExpressions:
                - key: node
                  operator: In
                  values:
                    - node1 #label value
